### ISSUE TITLE
apt repo reports hash missmatch (Duplicate opf closed issue #5530)

### ISSUE THREAD

**Issue by urbanadventurer** [google/gvisor#5635]
**Description**

apt repo hashes do not match the deb package! This issue was previously reported as #5530 and was closed.

**Steps to reproduce**

```
add-apt-repository "deb https://storage.googleapis.com/gvisor/releases release main"
sudo apt-get update && sudo apt-get install -y runsc
Hit:1 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:2 https://storage.googleapis.com/gvisor/releases ./release InRelease                                                                                   
Hit:3 https://packages.cloud.google.com/apt kubernetes-xenial InRelease                                                                      
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                     
Hit:5 http://us.archive.ubuntu.com/ubuntu bionic InRelease               
Hit:6 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  runsc
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 25.8 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://storage.googleapis.com/gvisor/releases ./release/main amd64 runsc amd64 20210301.0 [25.8 MB]
Err:1 https://storage.googleapis.com/gvisor/releases ./release/main amd64 runsc amd64 20210301.0
  Hash Sum mismatch
  Hashes of expected file:
   - SHA512:626f57ee8674362e15c15c65bd5d1654d3409900ac69305362f437c0e09b9a3b073cc02b94039cf278496d984b93d0109aa4c96df5ca58e4d627d847f91c68b0
   - SHA256:159faf0d992a3539c9a720515503e046436fc9074a4da712ea4927085e458b4c
   - SHA1:97f3cb5565947031dda6b151b9d343af2ef724c3 [weak]
   - MD5Sum:fe1064bb5b139d92a21b5d3dab10efae [weak]
   - Filesize:25821902 [weak]
  Hashes of received file:
   - SHA512:8ee3f1033cb17326180ac2c9aeae2c743ef6df5ddfac3ff9be900357dd849f4b949596c8c6edfb969b07004099a0e68a2ca254af9b92ea08e80d6c554ca5cc35
   - SHA256:9b1321d35faf8abf7705dca21d09dda42abf34f3afb2d36a2668cdc4aca724a8
   - SHA1:793b07d69a5783329946f320978effb13160d4d6 [weak]
   - MD5Sum:5954c994dcccd5ea0531abd1b363c329 [weak]
   - Filesize:25821902 [weak]
  Last modification reported: Wed, 03 Mar 2021 01:07:10 +0000
Fetched 25.8 MB in 4s (6,392 kB/s)
E: Failed to fetch https://storage.googleapis.com/gvisor/releases/pool/20210301.0/binary-amd64/runsc.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:626f57ee8674362e15c15c65bd5d1654d3409900ac69305362f437c0e09b9a3b073cc02b94039cf278496d984b93d0109aa4c96df5ca58e4d627d847f91c68b0
    - SHA256:159faf0d992a3539c9a720515503e046436fc9074a4da712ea4927085e458b4c
    - SHA1:97f3cb5565947031dda6b151b9d343af2ef724c3 [weak]
    - MD5Sum:fe1064bb5b139d92a21b5d3dab10efae [weak]
    - Filesize:25821902 [weak]
   Hashes of received file:
    - SHA512:8ee3f1033cb17326180ac2c9aeae2c743ef6df5ddfac3ff9be900357dd849f4b949596c8c6edfb969b07004099a0e68a2ca254af9b92ea08e80d6c554ca5cc35
    - SHA256:9b1321d35faf8abf7705dca21d09dda42abf34f3afb2d36a2668cdc4aca724a8
    - SHA1:793b07d69a5783329946f320978effb13160d4d6 [weak]
    - MD5Sum:5954c994dcccd5ea0531abd1b363c329 [weak]
    - Filesize:25821902 [weak]
   Last modification reported: Wed, 03 Mar 2021 01:07:10 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Check the deb file
```
wget https://storage.googleapis.com/gvisor/releases/pool/20210301.0/binary-amd64/runsc.deb 
--2021-03-08 21:32:47--  https://storage.googleapis.com/gvisor/releases/pool/20210301.0/binary-amd64/runsc.deb
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.25.144, 216.58.196.144, 216.58.200.112, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.25.144|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25821902 (25M) [application/octet-stream]
Saving to: ‘runsc.deb’

runsc.deb                        100%[========================================================>]  24.62M  10.3MB/s    in 2.4s    

2021-03-08 21:32:50 (10.3 MB/s) - ‘runsc.deb’ saved [25821902/25821902]

sha1sum runsc.deb 
793b07d69a5783329946f320978effb13160d4d6  runsc.deb

```

Compare with apt lists

```
andrew@ubuntu:/var/lib/apt/lists$ cat storage.googleapis.com_gvisor_releases_dists_._release_main_binary-amd64_Packages 
Package: runsc
Architecture: amd64
Version: 20210301.0
Priority: optional
Section: contrib/devel
Maintainer: The gVisor Authors <gvisor-dev@googlegroups.com>
Filename: pool/20210301.0/binary-amd64/runsc.deb
Size: 25821902
MD5sum: fe1064bb5b139d92a21b5d3dab10efae
SHA1: 97f3cb5565947031dda6b151b9d343af2ef724c3
SHA256: 159faf0d992a3539c9a720515503e046436fc9074a4da712ea4927085e458b4c
SHA512: 626f57ee8674362e15c15c65bd5d1654d3409900ac69305362f437c0e09b9a3b073cc02b94039cf278496d984b93d0109aa4c96df5ca58e4d627d847f91c68b0
Homepage: https://gvisor.dev/
Description: gVisor container sandbox runtime

```

**Environment**

- Fresh install of Ubuntu 18.04
- `Linux ubuntu 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Working Workaround***

Use an older version.

```
add-apt-repository "deb https://storage.googleapis.com/gvisor/releases 20201208 main"
sudo apt-get update && sudo apt-get install -y runsc
Hit:1 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:2 https://storage.googleapis.com/gvisor/releases 20201208 InRelease                                                                                    
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic InRelease                                                                                                 
Hit:3 https://packages.cloud.google.com/apt kubernetes-xenial InRelease                                                             
Hit:5 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                         
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease        
Hit:7 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease     
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  runsc
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 31.3 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://storage.googleapis.com/gvisor/releases 20201208/main amd64 runsc amd64 20201208.0 [31.3 MB]
Fetched 31.3 MB in 4s (7,270 kB/s)
Selecting previously unselected package runsc.
(Reading database ... 165813 files and directories currently installed.)
Preparing to unpack .../runsc_20201208.0_amd64.deb ...
Unpacking runsc (20201208.0) ...
Setting up runsc (20201208.0) ...

```

**Comment by markxp** [comment]
Same result, with the environment:

distro: Debian 10
kernel: Linux proton-XozRd 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

**Comment by Bo0km4n** [comment]
Same result occurred.
My environment:
```
$ apt --version
apt 1.6.12ubuntu0.2 (amd64)

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by avagin** [comment]
https://github.com/google/gvisor/pull/5663 should fix this isse.

**Comment by amscanne** [comment]
Thanks @avagin for the fix, that was making me crazy. I've pinned the release again but hopefully this has gone away. Thanks for the report @Bo0km4n, @urbanadventurer, @markxp.

The issue was that that .deb file was signed correctly and the repository generated correctly, but then the deb was being resigned, changing the hashes. Maybe we should also just stop signing the debs? I believe the standard is now that people just sign the repository metadata anyways.

**Comment by nsoubelet** [comment]
Hello @amscanne, as far as I understand this is solved, right? I am having the same problem right now.
Same setup as users above, same distro and kernel version.
Is there any manual step I should do to fix it? Latest release is https://github.com/google/gvisor/releases/tag/release-20210301.0 so maybe it is not already fixed?
Thanks

**Comment by markxp** [comment]
@nsoubelet @amscanne It is not fixed yet. All messages (Debian 10, kernel 4.19) were the same as @urbanadventurer posted.
Maybe it's not pushed yet? 

```
Get:1 https://storage.googleapis.com/gvisor/releases release/main amd64 runsc amd64 20210301.0 [25.8 MB]
Err:1 https://storage.googleapis.com/gvisor/releases release/main amd64 runsc amd64 20210301.0
  Hash Sum mismatch
  Hashes of expected file:
   - SHA512:626f57ee8674362e15c15c65bd5d1654d3409900ac69305362f437c0e09b9a3b073cc02b94039cf278496d984b93d0109aa4c96df5ca58e4d627d847f91c68b0
   - SHA256:159faf0d992a3539c9a720515503e046436fc9074a4da712ea4927085e458b4c
   - SHA1:97f3cb5565947031dda6b151b9d343af2ef724c3 [weak]
   - MD5Sum:fe1064bb5b139d92a21b5d3dab10efae [weak]
   - Filesize:25821902 [weak]
  Hashes of received file:
   - SHA512:8ee3f1033cb17326180ac2c9aeae2c743ef6df5ddfac3ff9be900357dd849f4b949596c8c6edfb969b07004099a0e68a2ca254af9b92ea08e80d6c554ca5cc35
   - SHA256:9b1321d35faf8abf7705dca21d09dda42abf34f3afb2d36a2668cdc4aca724a8
   - SHA1:793b07d69a5783329946f320978effb13160d4d6 [weak]
   - MD5Sum:5954c994dcccd5ea0531abd1b363c329 [weak]
   - Filesize:25821902 [weak]
  Last modification reported: Wed, 03 Mar 2021 01:07:10 +0000
Fetched 25.8 MB in 3s (7,541 kB/s)
E: Failed to fetch https://storage.googleapis.com/gvisor/releases/pool/20210301.0/binary-amd64/runsc.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:626f57ee8674362e15c15c65bd5d1654d3409900ac69305362f437c0e09b9a3b073cc02b94039cf278496d984b93d0109aa4c96df5ca58e4d627d847f91c68b0
    - SHA256:159faf0d992a3539c9a720515503e046436fc9074a4da712ea4927085e458b4c
    - SHA1:97f3cb5565947031dda6b151b9d343af2ef724c3 [weak]
    - MD5Sum:fe1064bb5b139d92a21b5d3dab10efae [weak]
    - Filesize:25821902 [weak]
   Hashes of received file:
    - SHA512:8ee3f1033cb17326180ac2c9aeae2c743ef6df5ddfac3ff9be900357dd849f4b949596c8c6edfb969b07004099a0e68a2ca254af9b92ea08e80d6c554ca5cc35
    - SHA256:9b1321d35faf8abf7705dca21d09dda42abf34f3afb2d36a2668cdc4aca724a8
    - SHA1:793b07d69a5783329946f320978effb13160d4d6 [weak]
    - MD5Sum:5954c994dcccd5ea0531abd1b363c329 [weak]
    - Filesize:25821902 [weak]
   Last modification reported: Wed, 03 Mar 2021 01:07:10 +0000
```

**Comment by avagin** [comment]
@nsoubelet @markxp you need to wait for the next release.

**Comment by nsoubelet** [comment]
Hi guys, yes it is now working. I was forced to run a `dpkg --configure -a` because when having gvidor repo I had some `dpkg was interrupted` but I think it was a problem related to my OS, not a general thing.

Thanks

**Comment by metala** [comment]
Can we reopen it?

```
$ sudo apt upgrade 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  runsc
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 26.9 MB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://storage.googleapis.com/gvisor/releases release/main amd64 runsc amd64 20220309.0 [26.9 MB]
Err:1 https://storage.googleapis.com/gvisor/releases release/main amd64 runsc amd64 20220309.0
  Hash Sum mismatch
  Hashes of expected file:
   - SHA512:df9f17705cdd972c3b571c54aa1acc602bd52d33466ee1e4ead082a7836025134f349e78dfca628e1c96fde8c56711ef757903160dd33ae4f7d6aa89097c6bd6
   - SHA256:9a5f621d809a5501d078f970ceffd13da2269b21d54008ff3d0c91a8f1aba68b
   - SHA1:5560c9d3a2bf4c9efbe1a5bb25b93f77a03d917e [weak]
   - MD5Sum:f927e28c0951d93e25ecb6c3abaeb5ce [weak]
   - Filesize:26928690 [weak]
  Hashes of received file:
   - SHA512:da0fe5dfc1fc3fa595dcd549aea3852c3b7349aa7b268ece206b3490f8a6093ae8a078651d08c6881762b918a97ff2b38ad0ef11c7cbc370a3de8a49780d3cfc
   - SHA256:13f41dc92775528ff1b4aab9b0dfae23fa14327e582caf9b331ada7b6b27bccd
   - SHA1:a7044cfe68d7a92445f39f244ddc0489e5c9101d [weak]
   - MD5Sum:c17bded79d14b59d5774fec975bdffd0 [weak]
   - Filesize:26928690 [weak]
  Last modification reported: Fri, 29 Apr 2022 21:48:57 +0000
Fetched 26.9 MB in 1s (18.8 MB/s)
E: Failed to fetch https://storage.googleapis.com/gvisor/releases/pool/20220309.0/binary-amd64/runsc.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:df9f17705cdd972c3b571c54aa1acc602bd52d33466ee1e4ead082a7836025134f349e78dfca628e1c96fde8c56711ef757903160dd33ae4f7d6aa89097c6bd6
    - SHA256:9a5f621d809a5501d078f970ceffd13da2269b21d54008ff3d0c91a8f1aba68b
    - SHA1:5560c9d3a2bf4c9efbe1a5bb25b93f77a03d917e [weak]
    - MD5Sum:f927e28c0951d93e25ecb6c3abaeb5ce [weak]
    - Filesize:26928690 [weak]
   Hashes of received file:
    - SHA512:da0fe5dfc1fc3fa595dcd549aea3852c3b7349aa7b268ece206b3490f8a6093ae8a078651d08c6881762b918a97ff2b38ad0ef11c7cbc370a3de8a49780d3cfc
    - SHA256:13f41dc92775528ff1b4aab9b0dfae23fa14327e582caf9b331ada7b6b27bccd
    - SHA1:a7044cfe68d7a92445f39f244ddc0489e5c9101d [weak]
    - MD5Sum:c17bded79d14b59d5774fec975bdffd0 [weak]
    - Filesize:26928690 [weak]
   Last modification reported: Fri, 29 Apr 2022 21:48:57 +0000
```

**Comment by amscanne** [comment]
Shoot, I did a backfill today for #7327, let me see what could have happened here.

**Comment by amscanne** [comment]
I think there may have been a race in the backfill, and things seem to be working as expected for me now. Can you confirm whether this is the case for you?

**Comment by tankaras** [comment]
Reopen. Am facing issue

```
sudo apt upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  linux-headers-5.17.5-051705 linux-headers-5.17.5-051705-generic linux-image-unsigned-5.17.5-051705-generic
  linux-modules-5.17.5-051705-generic
The following packages will be upgraded:
  linux-generic-5.17 runsc
2 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.2 MB/133 MB of archives.
After this operation, 661 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://storage.googleapis.com/gvisor/releases release/main amd64 runsc amd64 20220425.0 [27.2 MB]
Err:1 https://storage.googleapis.com/gvisor/releases release/main amd64 runsc amd64 20220425.0
  Hash Sum mismatch
  Hashes of expected file:
   - SHA512:bb6a803d916fac425ec057cc4288c35b9b562bac333ef313b5197435db42cefd96736d43da148e7a6a05b820855fb328038437f2e265137deeb80bdc75d0b485
   - SHA256:d6f57011c81c495593c2ec2d5db1a7fc24ea51cd4f9872c3e3fae34186f67f71
   - SHA1:d64838acd3934de783694271710a898fcdc80886 [weak]
   - MD5Sum:ae05f6f5c2dc11b9aa5cf16d835f8bc9 [weak]
   - Filesize:27249546 [weak]
  Hashes of received file:
   - SHA512:5f1e687559be74ab76e62546f57a2ac7fb8c9abc436ba9a4d582d298dc0e0b79835757b1917dcd07b61fa9c8b1b87e789ae13da2866149383a2e50dc7198e9d6
   - SHA256:cbdfbe22df713078b0890681cedf05e301054d563a59e9450949c32dc01d0c28
   - SHA1:dda883cf1b762a23ae6d4d47176710c7a0876046 [weak]
   - MD5Sum:6fb618258a14abb6afd265a99be9e69e [weak]
   - Filesize:27249546 [weak]
  Last modification reported: Fri, 29 Apr 2022 23:41:39 +0000
Fetched 27.2 MB in 1s (23.4 MB/s)
E: Failed to fetch https://storage.googleapis.com/gvisor/releases/pool/20220425.0/binary-amd64/runsc.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:bb6a803d916fac425ec057cc4288c35b9b562bac333ef313b5197435db42cefd96736d43da148e7a6a05b820855fb328038437f2e265137deeb80bdc75d0b485
    - SHA256:d6f57011c81c495593c2ec2d5db1a7fc24ea51cd4f9872c3e3fae34186f67f71
    - SHA1:d64838acd3934de783694271710a898fcdc80886 [weak]
    - MD5Sum:ae05f6f5c2dc11b9aa5cf16d835f8bc9 [weak]
    - Filesize:27249546 [weak]
   Hashes of received file:
    - SHA512:5f1e687559be74ab76e62546f57a2ac7fb8c9abc436ba9a4d582d298dc0e0b79835757b1917dcd07b61fa9c8b1b87e789ae13da2866149383a2e50dc7198e9d6
    - SHA256:cbdfbe22df713078b0890681cedf05e301054d563a59e9450949c32dc01d0c28
    - SHA1:dda883cf1b762a23ae6d4d47176710c7a0876046 [weak]
    - MD5Sum:6fb618258a14abb6afd265a99be9e69e [weak]
    - Filesize:27249546 [weak]
   Last modification reported: Fri, 29 Apr 2022 23:41:39 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```

**Comment by metala** [comment]
> I think there may have been a race in the backfill, and things seem to be working as expected for me now. Can you confirm whether this is the case for you?

Not really.
```
$ sudo apt dist-upgrade 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  runsc
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.2 MB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://storage.googleapis.com/gvisor/releases release/main amd64 runsc amd64 20220425.0 [27.2 MB]
Err:1 https://storage.googleapis.com/gvisor/releases release/main amd64 runsc amd64 20220425.0
  Hash Sum mismatch
  Hashes of expected file:
   - SHA512:bb6a803d916fac425ec057cc4288c35b9b562bac333ef313b5197435db42cefd96736d43da148e7a6a05b820855fb328038437f2e265137deeb80bdc75d0b485
   - SHA256:d6f57011c81c495593c2ec2d5db1a7fc24ea51cd4f9872c3e3fae34186f67f71
   - SHA1:d64838acd3934de783694271710a898fcdc80886 [weak]
   - MD5Sum:ae05f6f5c2dc11b9aa5cf16d835f8bc9 [weak]
   - Filesize:27249546 [weak]
  Hashes of received file:
   - SHA512:5f1e687559be74ab76e62546f57a2ac7fb8c9abc436ba9a4d582d298dc0e0b79835757b1917dcd07b61fa9c8b1b87e789ae13da2866149383a2e50dc7198e9d6
   - SHA256:cbdfbe22df713078b0890681cedf05e301054d563a59e9450949c32dc01d0c28
   - SHA1:dda883cf1b762a23ae6d4d47176710c7a0876046 [weak]
   - MD5Sum:6fb618258a14abb6afd265a99be9e69e [weak]
   - Filesize:27249546 [weak]
  Last modification reported: Fri, 29 Apr 2022 23:41:39 +0000
Fetched 27.2 MB in 1s (20.6 MB/s)
E: Failed to fetch https://storage.googleapis.com/gvisor/releases/pool/20220425.0/binary-amd64/runsc.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:bb6a803d916fac425ec057cc4288c35b9b562bac333ef313b5197435db42cefd96736d43da148e7a6a05b820855fb328038437f2e265137deeb80bdc75d0b485
    - SHA256:d6f57011c81c495593c2ec2d5db1a7fc24ea51cd4f9872c3e3fae34186f67f71
    - SHA1:d64838acd3934de783694271710a898fcdc80886 [weak]
    - MD5Sum:ae05f6f5c2dc11b9aa5cf16d835f8bc9 [weak]
    - Filesize:27249546 [weak]
   Hashes of received file:
    - SHA512:5f1e687559be74ab76e62546f57a2ac7fb8c9abc436ba9a4d582d298dc0e0b79835757b1917dcd07b61fa9c8b1b87e789ae13da2866149383a2e50dc7198e9d6
    - SHA256:cbdfbe22df713078b0890681cedf05e301054d563a59e9450949c32dc01d0c28
    - SHA1:dda883cf1b762a23ae6d4d47176710c7a0876046 [weak]
    - MD5Sum:6fb618258a14abb6afd265a99be9e69e [weak]
    - Filesize:27249546 [weak]
   Last modification reported: Fri, 29 Apr 2022 23:41:39 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by bduffany** [comment]
This is reproducible on debian 11:

```
docker run --rm -it debian:11

apt-get update
apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg
curl -fsSL https://gvisor.dev/archive.key | gpg --dearmor -o /usr/share/keyrings/gvisor-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/gvisor-archive-keyring.gpg] https://storage.googleapis.com/gvisor/releases release main" | \
  tee /etc/apt/sources.list.d/gvisor.list > /dev/null
apt-get update && apt-get install -y runsc
```

**Comment by amscanne** [comment]
Thanks, the repro is helpful here. I'm not sure why it's working for me. I'm trying to understand what exactly is going wrong but hope to have it fixed soon.

**Comment by amscanne** [comment]
I think I've found and fixed the issue. I've fixed the "release" distribution, but there may be a warning until the next release is published.

**Comment by metala** [comment]
@amscanne Thanks, all good now.

```$ sudo apt upgrade 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  runsc
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.2 MB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://storage.googleapis.com/gvisor/releases release/main amd64 runsc amd64 20220425.0 [27.2 MB]
Fetched 27.2 MB in 1s (18.6 MB/s) 
Reading changelogs... Done
(Reading database ... 250180 files and directories currently installed.)
Preparing to unpack .../runsc_20220425.0_amd64.deb ...
Unpacking runsc (20220425.0) over (20220228.0) ...
Setting up runsc (20220425.0) ...
2022/05/02 23:06:15 Added runtime "runsc" with arguments [] to "/etc/docker/daemon.json".
/var/lib/dpkg/info/runsc.postinst: 24: systemctl: not found```

PS. did you just assume I have systemd? j/k
